##############################
# Variables you need to change
##############################

#Change "sampleA", "sampleB" to the output naming prefix for your assemblies (e.g. species name)
#For the "hifi", "nanopore" etc. fields, if multiple read files put path to reads as comma separated list
#"hifi" XOR "nanopore"
#If using HiC, must have both hic1 and hic2
#If don't have relevant data types, REMOVE that line 
samples:
  sampleA:
    hifi: ["../testing/data/sampA_pacbio_1.bam", "../testing/data/sampA_pacbio_1.bam"]
    readFileType: "bam"
    ultralong: "../testing/data/sampA_UL.fastq"
    hic1: "../testing/data/sampA_hic1.fastq"
    hic2: "../testing/data/sampA_hic1.fastq"
  sampleB:
    nanopore: ["../testing/data/sampB_nanopore_1.fastq", "../testing/data/sampB_nanopore_2.fastq"]
    readFileType: "fastq"
    ultralong: "../testing/data/sampB_UL.fastq"

#Optional: for running BUSCO using compleasm, specify a lineage (defaults to autolineage)
#Note: sample IDs must match the IDs above!
busco:
  sampleA: "auto"
  sampleB: "ciliophora_odb12"


#Variables you DON'T need to change:
#Output naming:
intermediate_outdir: "results/intermediate_files"
hifi_outdir: "results/hifiasm_output_RAW"
assem_outdir: "results/assembly"
