##############################
# Variables you need to change
##############################

sample: "sample_206_npict"               #Name of the sample to act as base name
reads:
  A: /n/holyscratch01/informatics/dkhost/bird_hifi/sample_206_reads/m64155e_220728_110902.read.fastq
  B: /n/holyscratch01/informatics/dkhost/bird_hifi/sample_206_reads/m64155e_220811_192258.reads.fastq

#Hifiasm options
use_hiC: "false"  #Indicate whether using HiC data to aid in with assembly (note, NOT the same as HiC scaffolding!)
hiC_read1: " "  #If using HiC,
hiC_read2: " "

primary_only: "false"

#Variables you DON'T need to change:
#Output naming:
hifi_outdir: "results/hifiasm_output_RAW"
assem_outdir: "results/assembly"
