##############################
# Variables you need to change
##############################

#Change "sampleA", "sampleB" to the output naming prefix for your assemblies (e.g. species name)
#For the "hifi", "nanopore" etc. fields, put path to reads as comma separated list
#"hifi" XOR "nanopore"
#If using HiC, must have both hic1 and hic2
#If don't have relevant data types, REMOVE that line 
samples:
  sampleA:
    hifi: ["path/to/reads.bam", "/path/to/reads2.bam"]
    readFileType: "bam|fastq"
    ultralong:
    hic1:
    hic2:
  sampleB:
    nanopore: ["path/to/reads.bam", "/path/to/reads2.bam"]
    readFileType:
    ultralong:
    hic1:
    hic2:

#Optional: for running BUSCO using compleasm, specify a lineage (defaults to autolineage)
#Note: sample IDs must match the IDs above!
busco:
  sampleA: "auto"
  sampleB: "auto"


#Variables you DON'T need to change:
#Output naming:
intermediate_outdir: "results/intermediate_files"
hifi_outdir: "results/hifiasm_output_RAW"
assem_outdir: "results/assembly"
