##############################
# Variables you need to change
##############################

sample: "MCZ_Cryo"               #Name of the sample to act as base name
reads: "path/to/reads.fastq"           #Reads used to generate assembly; if multiple files, separate them by SPACES

#Hifiasm options
use_hiC: "false"  #Indicate whether using HiC data to aid in with assembly (note, NOT the same as HiC scaffolding!)
hiC_read1: " "  #If using HiC,
hiC_read2: " "

primary_only: "false"

#Variables you DON'T need to change:
#Output naming:
hifi_outdir: "results/hifiasm_output_RAW"
assem_outdir: "results/assembly"
