bam2fastq:
    nodes: 1 
    threads: 2
    mem_mb: 36000
    time: 4320

adapterfilt:
    nodes: 1 
    threads: 4
    mem_mb: 36000
    time: 4320

hifiasm:
    nodes: 1 
    threads: 16
    mem_mb: 800000
    time: 20160

gfatofasta:
    nodes: 1 
    threads: 1
    mem_mb: 16000
    time: 720

renamecontigs:
    nodes: 1 
    threads: 1
    mem_mb: 16000
    time: 720

quast:
    nodes: 1 
    threads: 2
    mem_mb: 16000
    time: 720