__default__:
    partition: "shared"
    time: 720
    nodes: 1
    output: "workflow/logs/slurm-%j.out"
    error: "workflow/logs/slurm-%j.err"

bam2fastx:
    partition: "shared" 
    output: "workflow/logs/bam2fastx-%j.out"
    error: "workflow/logs/bam2fastx-%j.err"
    job-name: "bam2fastx"

adapterfilt:
    partition: "shared" 
    output: "workflow/logs/adadpterfilt-%j.out"
    error: "workflow/logs/adapterfilt-%j.err"
    job-name: "adapterfilt"

hifiasm:
    partition: "holy-cow,intermediate" 
    output: "workflow/logs/hifiasm-%j.out"
    error: "workflow/logs/hifiasm-%j.err"
    job-name: "hifiasm"

gfa_to_fasta:
    partition: "shared" 
    output: "workflow/logs/gfatofasta-%j.out"
    error: "workflow/logs/gfatofasta-%j.err"
    job-name: "gfatofasta"

rename_contig:
    partition: "shared" 
    output: "workflow/logs/rename-%j.out"
    error: "workflow/logs/rename-%j.err"
    job-name: "rename"

quast:
    partition: "shared" 
    output: "workflow/logs/quast-%j.out"
    error: "workflow/logs/quast-%j.err"
    job-name: "quast"