executor: slurm
jobs: 100

default-resources:
  slurm_account: 'informatics'
  slurm_partition: 'shared'

set-threads:
  bam2fastq: 1
  adapterfilt: 4
  hifiasm: 20
  gfatofasta: 1
  renamecontigs: 1
  quast: 4

set-resources:
  bam2fastq:
    nodes: 1
    tasks: 1 
    cpus_per_task: 1
    mem_mb: 36000
    runtime: 4320
    slurm_partition: "shared"
  adapterfilt:
    nodes: 1
    tasks: 1
    cpus_per_task: 4
    mem_mb: 36000
    runtime: 4320
    slurm_partition: "shared"
  hifiasm:
    nodes: 1
    tasks: 1
    cpus_per_task: 20
    mem_mb: 400000
    runtime: 20160
    slurm_partition: "holy-cow,intermediate"
  gfa_to_fasta:
    nodes: 1
    tasks: 1
    cpus_per_task: 1
    mem_mb: 16000
    runtime: 720
    slurm_partition: "shared"
  rename_contigs:
    nodes: 1
    tasks: 1
    cpus_per_task: 1
    mem_mb: 8000
    runtime: 720
    slurm_partition: "shared"
  quast:
    nodes: 1
    tasks: 1
    cpus_per_task: 4
    mem_mb: 16000
    runtime: 720
    slurm_partition: "shared"

